services:
  php-fpm:
    image: apuntate-php-fpm
    build:
      context: ./apps/back
      dockerfile: etc/docker/php-fpm/dev/Dockerfile
    container_name: apuntate-php-fpm
    depends_on:
      - pgsql
    working_dir: /var/www/html
    user: www-data

  frontend:
    image: node:24-alpine
    container_name: apuntate-frontend
    working_dir: /app
    command: sh -c "npm install && npx ng serve --host 0.0.0.0 --poll 2000 --disable-host-check"
    volumes:
      - ./apps/front:/app:delegated
      - frontend-node-modules:/app/node_modules
    environment:
      - APP_ENV=dev
      - API_URL=http://localhost:8081/api

  pgsql:
    image: apuntate-pgsql
    build:
      context: ./apps/back/etc/docker/postgres
    container_name: apuntate-pgsql
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: admin
      POSTGRES_DATABASES: apuntate apuntate_test
    volumes:
      - pgsql-data:/var/lib/postgresql/data

volumes:
  pgsql-data:
    driver: local
  frontend-node-modules:
    driver: local
