#index:
#    path: /
#    controller: GlobalEmergency\Apuntate\Controller\DefaultController::index
login_check:
  path:     /api/auth/login
  methods:  [POST]
  defaults:
    _format: json

gesdinet_jwt_refresh_token:
  path: /api/auth/refresh
  controller: gesdinet.jwtrefreshtoken:refresh
  methods:  [POST]
  defaults:
    _format: json

api_infra_routes:
  resource: ../src/Api/Infrastructure/Symfony/routes.yaml

app_swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app_swagger_json:
  path: /api/doc.json
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_json }
