# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.frontend_url: '%env(APP_FRONTEND_URL)%'
    app.mail_from: 'no-reply@globalemergency.es'
    app.mail_from_name: 'Apúntate - GlobalEmergency'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    GlobalEmergency\Apuntate\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    GlobalEmergency\Apuntate\Application\Services\EmailSenderInterface:
        alias: GlobalEmergency\Apuntate\Api\Infrastructure\Symfony\SymfonyEmailSender

    GlobalEmergency\Apuntate\Services\Normalizer\FlattenExceptionNormalizer:
        arguments:
            $appEnv: '%kernel.environment%'
        tags: ['serializer.normalizer']
