name: "Frontend: Lint and Test"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/front/**'
      - '.github/workflows/front-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/front
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint check
        run: npm run lint

      - name: Run tests
        run: npm run test
