name: "Frontend: Autodeploy main to prod"

on:
  push:
    branches:
      - main
    paths:
      - 'apps/front/**'
      - '.github/workflows/front-deploy.yaml'
      - '.github/workflows/front-autodeploy.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/front-deploy.yaml
    with:
      environment: "prod"
    secrets: inherit
